//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("6688f9b4-5f2d-4fd6-aafc-3a81c84a69f1")]
[assembly: AssemblyTitle("SolrNet.DSL")]
[assembly: AssemblyDescription("SolrNet.DSL")]
[assembly: AssemblyProduct("SolrNet.DSL")]
[assembly: AssemblyCopyright("Copyright Mauricio Scheffer 2007-2011")]
[assembly: AssemblyVersion("0.4.0.1001")]
[assembly: AssemblyFileVersion("0.4.0.1001")]
[assembly: AssemblyInformationalVersion("8a6f2f50663f803c18f9b2a4a23d53db670b321d")]
[assembly: AssemblyDelaySign(false)]


