version: '3.7'
services:
  solr:
    image: solr:8.8.2
    container_name: solr
    network_mode: host
    # logging:
    #  driver: none
    environment:
      ZK_HOST: localhost:9983
    depends_on:
      - zoo
  zoo:
    image: zookeeper
    container_name: zoo
    network_mode: host
    logging:
      driver: none
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo:2888:3888;9983
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
