//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("AutofacContrib.SolrNet")]
[assembly: AssemblyDescription("AutofacContrib.SolrNet")]
[assembly: AssemblyProduct("AutofacContrib.SolrNet")]
[assembly: AssemblyCopyright("Copyright © Mauricio Scheffer 2007-2010")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("4dedcda1-6a79-4aa0-8174-7fa573fa91f4")]
[assembly: AssemblyVersion("0.3.0")]
[assembly: AssemblyFileVersion("0.3.0")]


