//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("6688f9b4-5f2d-4fd6-aafc-3a81c84a69f1")]
[assembly: AssemblyTitle("Castle.Facilities.SolrNetIntegration")]
[assembly: AssemblyDescription("Castle.Facilities.SolrNetIntegration")]
[assembly: AssemblyProduct("Castle.Facilities.SolrNetIntegration")]
[assembly: AssemblyCopyright("Copyright Mauricio Scheffer 2007-2015")]
[assembly: AssemblyVersion("0.4.0.4001")]
[assembly: AssemblyFileVersion("0.4.0.4001")]
[assembly: AssemblyInformationalVersion("17bf323fdcbbee137ca44af080426ea0b28cb626")]
[assembly: AssemblyDelaySign(false)]


