//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("6688f9b4-5f2d-4fd6-aafc-3a81c84a69f1")]
[assembly: AssemblyTitle("Ninject.Integration.SolrNet")]
[assembly: AssemblyDescription("Ninject.Integration.SolrNet")]
[assembly: AssemblyProduct("Ninject.Integration.SolrNet")]
[assembly: AssemblyCopyright("Copyright Mauricio Scheffer 2007-2011")]
[assembly: AssemblyVersion("0.3.0")]
[assembly: AssemblyFileVersion("0.3.1")]
[assembly: AssemblyInformationalVersion("edd00288ce093a93770c1484908a91118fa8fb2d")]
[assembly: AssemblyDelaySign(false)]


