//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("6688f9b4-5f2d-4fd6-aafc-3a81c84a69f1")]
[assembly: AssemblyTitle("Unity.SolrNetIntegration.Tests")]
[assembly: AssemblyDescription("Unity.SolrNetIntegration.Tests")]
[assembly: AssemblyProduct("Unity.SolrNetIntegration.Tests")]
[assembly: AssemblyCopyright("Copyright Mauricio Scheffer 2007-2011")]
[assembly: AssemblyVersion("0.4.0")]
[assembly: AssemblyFileVersion("0.4.0")]
[assembly: AssemblyInformationalVersion("700848dfed40d67bd59339dd046012bd3b5202f6")]
[assembly: AssemblyDelaySign(false)]


